steps:
  ### Build the Trusted OS, create a detached signature for it, and upload both to GCS.
  # Build an image containing the Trusted OS artifacts with the Dockerfile.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TAMAGO_VERSION=${_TAMAGO_VERSION}
      - -t
      - builder-image
      # Path is relative to the root of the repo.
      - .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build/bin
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # Copy the artifacts from the Cloud Build VM to GCS.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - gcloud
      - storage
      - cp
      - output/trusted_os.elf
      - gs://${_FIRMWARE_BUCKET}/$(sha256sum output/trusted_os.elf | cut -f1 -d" ")
  ### Construct log entry / Claimant Model statement.
  - name: golang
    args:
      - go
      - get
      - github.com/transparency-dev/armored-witness/cmd/manifest
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/manifest
      - create
      - --git_tag=${_TEST_TAG_NAME}
      - --git_commit_fingerprint=${COMMIT_SHA}
      - --firmware_file=output/trusted_os.elf
      - --firmware_type=TRUSTED_OS
      - --tamago_version=${_TAMAGO_VERSION}
      - --raw
      - --output_file=output/trusted_os_manifest_unsigned.json
  # Sign the log entry.
  # TODO: sign the manifest twice to mimic the WithSecure 2nd signature flow.
  - name: golang
    args:
      - go
      - get
      - github.com/transparency-dev/armored-witness/cmd/sign
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/sign
      - --project_name=${PROJECT_ID}
      - --release="ci"
      - --artefact="os1"
      - --manifest_file=output/trusted_os_manifest_unsigned.json
      - --output_file=output/trusted_os_manifest_transparency_dev
  # Print the content of the signed manifest.
  - name: bash
    args:
      - cat
      - output/trusted_os_manifest_transparency_dev
  ### Write the firmware release to the CI transparency log.
  # Copy the signed note to the sequence bucket, preparing to write to log.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - storage
      - cp
      - output/trusted_os_manifest_transparency_dev
      - gs://${_LOG_NAME}/${_ENTRIES_DIR}/trusted_os_manifest
  # Sequence log entry.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - call
      - sequence
      - '--data'
      - '{"entriesDir": "${_ENTRIES_DIR}", "origin": "${_ORIGIN}", "bucket": "${_LOG_NAME}"}'
  # Integrate log entry.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - call
      - integrate
      - '--data'
      - '{"origin": "${_ORIGIN}", "bucket": "${_LOG_NAME}"}'
substitutions:
  # Build-related.
  _FIRMWARE_BUCKET: armored-witness-firmware-ci
  _FIRMWARE_COMPONENT: trusted-os
  _TAMAGO_VERSION: '1.20.6'
  _TEST_TAG_NAME: '0.1.2'
  # Log-related.
  _ENTRIES_DIR: firmware-log-sequence
  _ORIGIN: transparency.dev/armored-witness/firmware_transparency/ci/0
  _LOG_NAME: armored-witness-firmware-log-ci
