steps:
  # First create a fake tag we'll use throughout the CI build process below.
  # Unfortunately, GCB has no concept of dynamically creating substitutions or
  # passing ENV vars between steps, so the best we can do is to create a file
  # containing our tag in the share workspace which other steps can inspect.
  - name: bash
    script: |
      date +'0.2.%s-incompatible' > /workspace/fake_tag
      cat /workspace/fake_tag
  ### Build the Trusted OS, create a detached signature for it, and upload both to GCS.
  # Build an image containing the Trusted OS artifacts with the Dockerfile.
  # This step needs to be a bash script in order to substitute fake tag into a
  # build arg.
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg=TAMAGO_VERSION=${_TAMAGO_VERSION} \
          --build-arg=LOG_ORIGIN=${_ORIGIN} \
          --build-arg=LOG_PUBLIC_KEY=${_LOG_PUBLIC_KEY} \
          --build-arg=APPLET_PUBLIC_KEY=${_APPLET_PUBLIC_KEY} \
          --build-arg=GIT_SEMVER_TAG=$(cat /workspace/fake_tag) \
          -t builder-image \
          .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build/bin
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # Copy the artifacts from the Cloud Build VM to GCS.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp \
          output/trusted_os.elf \
          gs://${_FIRMWARE_BUCKET}/$(sha256sum output/trusted_os.elf | cut -f1 -d" ")
  ### Construct log entry / Claimant Model statement.
  # Create the manifest.
  # This step needs to be a bash script in order to substitute the fake take
  # in the command args.
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/transparency-dev/armored-witness/cmd/manifest@${_ARMORED_WITNESS_REPO_VERSION} \
          create \
          --git_tag=$(cat /workspace/fake_tag) \
          --git_commit_fingerprint=${COMMIT_SHA} \
          --firmware_file=output/trusted_os.elf \
          --firmware_type=TRUSTED_OS \
          --tamago_version=${_TAMAGO_VERSION} \
          --raw \
          --output_file=output/trusted_os_manifest_unsigned.json
  # Sign the log entry.
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/sign@${_ARMORED_WITNESS_REPO_VERSION}
      - --project_name=${PROJECT_ID}
      - --release=ci
      - --artefact=os1
      - --manifest_file=output/trusted_os_manifest_unsigned.json
      - --output_file=output/trusted_os_manifest_transparency_dev
  # Countersign the log entry to fake a WS signature for CI
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/sign@${_ARMORED_WITNESS_REPO_VERSION}
      - --project_name=${PROJECT_ID}
      - --release=ci
      - --artefact=os2
      - --note_file=output/trusted_os_manifest_transparency_dev
      - --note_verifier=${_OS_PUBLIC_KEY1}
      - --output_file=output/trusted_os_manifest_both
  # Print the content of the signed manifest.
  - name: bash
    args:
      - cat
      - output/trusted_os_manifest_both
  ### Write the firmware release to the CI transparency log.
  # Copy the signed note to the sequence bucket, preparing to write to log.
  #
  # Use the SHA256 of the manifest as the name of the manifest. This allows
  # multiple triggers to run without colliding.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp output/trusted_os_manifest_both \
        gs://${_LOG_NAME}/${_ENTRIES_DIR}/$(sha256sum output/trusted_os_manifest_both | cut -f1 -d" ")
  # Sequence log entry.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - call
      - sequence
      - '--data'
      - >-
        {
          "entriesDir": "${_ENTRIES_DIR}",
          "origin": "${_ORIGIN}",
          "bucket": "${_LOG_NAME}",
          "kmsKeyName": "ft-log-ci",
          "kmsKeyRing": "firmware-release-ci",
          "kmsKeyVersion": ${_KEY_VERSION},
          "kmsKeyLocation": "global",
          "noteKeyName": "transparency.dev-aw-ftlog-ci",
          "checkpointCacheControl": "${_CHECKPOINT_CACHE}"
        }
  # Integrate log entry.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - call
      - integrate
      - '--data'
      - >-
        {
          "origin": "${_ORIGIN}",
          "bucket": "${_LOG_NAME}",
          "kmsKeyName": "ft-log-ci",
          "kmsKeyRing": "firmware-release-ci",
          "kmsKeyVersion": ${_KEY_VERSION},
          "kmsKeyLocation": "global",
          "noteKeyName": "transparency.dev-aw-ftlog-ci",
          "checkpointCacheControl": "${_CHECKPOINT_CACHE}"
        }
  # Clean up the file we added to the _ENTRIES_DIR bucket now that it's been
  # integrated to the log.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage rm \
        gs://${_LOG_NAME}/${_ENTRIES_DIR}/$(sha256sum output/trusted_os_manifest_both | cut -f1 -d" ")
substitutions:
  # Build-related.
  _FIRMWARE_BUCKET: armored-witness-firmware-ci-1
  _TAMAGO_VERSION: '1.21.3'
  _ARMORED_WITNESS_REPO_VERSION: e7141b6db638c3a2cb23e354cedd2d2980d0fb3a
  # Log-related.
  _ENTRIES_DIR: firmware-log-sequence
  # This must correspond with the trailing number on the _FIRMWARE_BUCKET, _ORIGIN, _LOG_NAME values.
  _KEY_VERSION: '1'
  _ORIGIN: transparency.dev/armored-witness/firmware_transparency/ci/1
  _LOG_NAME: armored-witness-firmware-log-ci-1
  _LOG_PUBLIC_KEY: transparency.dev-aw-ftlog-ci+f5479c1e+AR6gW0mycDtL17iM2uvQUThJsoiuSRirstEj9a5AdCCu
  _APPLET_PUBLIC_KEY: transparency.dev-aw-applet-ci+3ff32e2c+AV1fgxtByjXuPjPfi0/7qTbEBlPGGCyxqr6ZlppoLOz3
  _OS_PUBLIC_KEY1: transparency.dev-aw-os1-ci+7a0eaef3+AcsqvmrcKIbs21H2Bm2fWb6oFWn/9MmLGNc6NLJty2eQ
  _CHECKPOINT_CACHE: 'public, max-age=30'
