steps:
  ### Build the Trusted OS, create a detached signature for it, and upload both to GCS.
  # Build an image containing the Trusted OS artifacts with the Dockerfile.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - TAMAGO_VERSION=${_TAMAGO_VERSION}
      - -t
      - builder-image
      # Path is relative to the root of the repo.
      - .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build/bin
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # TODO(jayhou): change this to sign in the note format.
  # Sign the built OS.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - asymmetric-sign
      - --digest-algorithm
      - sha256
      - --version
      - ${_KMS_KEY_VERSION}
      - --key
      - ${_KMS_KEY}
      - --keyring
      - ${_KMS_KEYRING}
      - --location
      - ${_REGION}
      - --input-file
      - output/trusted_os.elf
      - --signature-file
      - output/trusted_os.sig
  # Copy the artifacts from the Cloud Build VM to GCS.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - storage
      - cp
      - output/trusted_os.elf
      - gs://${_FIRMWARE_BUCKET}/${_FIRMWARE_COMPONENT}/${_TEST_TAG_NAME}/firmware.elf
  - name: gcr.io/cloud-builders/gcloud
    args:
      - storage
      - cp
      - output/trusted_os.sig
      - gs://${_FIRMWARE_BUCKET}/${_FIRMWARE_COMPONENT}/${_TEST_TAG_NAME}/trusted_os_transparency_dev.sig
  ### Construct log entry / Claimant Model statement.
  - name: golang
    args:
      - go
      - get
      - github.com/transparency-dev/armored-witness/cmd/manifest
  - name: golang
    args:
      - go
      - run
      - github.com/transparency-dev/armored-witness/cmd/manifest
      - -git_tag=${_TEST_TAG_NAME}
      - -git_commit_fingerprint=${COMMIT_SHA}
      - -firmware_file=output/trusted_os.elf
      - -firmware_type=TRUSTED_OS
      - -tamago_version=${_TAMAGO_VERSION}
      - -output_file=output/trusted_os_manifest.json
  # Print the content of the manifest JSON.
  - name: bash
    args:
      - cat
      - output/trusted_os_manifest.json
  # Copy manifest JSON to the release bucket so that WithSecure may read it.
  - name: gcr.io/cloud-builders/gcloud
    args:
      - storage
      - cp
      - output/trusted_os_manifest.json
      - gs://${_FIRMWARE_BUCKET}/${_FIRMWARE_COMPONENT}/${_TEST_TAG_NAME}/trusted_os_manifest.json
substitutions:
  # Build-related.
  _FIRMWARE_BUCKET: armored-witness-firmware-ci
  _FIRMWARE_COMPONENT: trusted-os
  _TAMAGO_VERSION: '1.20.6'
  _TEST_TAG_NAME: '0.1.2'
  # Signing-related.
  _REGION: europe-west2
  _KMS_KEY: trusted-os-ci
  _KMS_KEYRING: armored-witness
  _KMS_KEY_VERSION: '1'
