steps:
  # First create a fake tag we'll use throughout the build process below.
  # Unfortunately, GCB has no concept of dynamically creating substitutions or
  # passing ENV vars between steps, so the best we can do is to create a file
  # containing our tag in the share workspace which other steps can inspect.
  - name: bash
    script: |
      date +'0.0.%s-incompatible' > /workspace/fake_tag
      cat /workspace/fake_tag
  ### Build the Trusted OS and upload it to GCS.
  # Build an image containing the Trusted OS artifacts with the Dockerfile.
  # This step needs to be a bash script in order to substitute fake tag into a
  # build arg.
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg=TAMAGO_VERSION=${_TAMAGO_VERSION} \
          --build-arg=LOG_ORIGIN=${_ORIGIN} \
          --build-arg=LOG_PUBLIC_KEY=${_LOG_PUBLIC_KEY} \
          --build-arg=APPLET_PUBLIC_KEY=${_APPLET_PUBLIC_KEY} \
          --build-arg=OS_PUBLIC_KEY1=${_OS_PUBLIC_KEY1} \
          --build-arg=OS_PUBLIC_KEY2=${_OS_PUBLIC_KEY2} \
          --build-arg=GIT_SEMVER_TAG=$(cat /workspace/fake_tag) \
          --build-arg=DEBUG=${_DEBUG} \
          -t builder-image \
          .
  # Prepare a container with a copy of the artifacts.
  - name: gcr.io/cloud-builders/docker
    args:
      - create
      - --name
      - builder_scratch
      - builder-image
  # Copy the artifacts from the container to the Cloud Build VM.
  - name: gcr.io/cloud-builders/docker
    args:
      - cp
      - builder_scratch:/build/bin
      - output
  # List the artifacts.
  - name: bash
    args:
      - ls
      - output
  # Copy the artifacts from the Cloud Build VM to GCS.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud storage cp \
          output/trusted_os.elf \
          gs://${_FIRMWARE_BUCKET}/$(sha256sum output/trusted_os.elf | cut -f1 -d" ")
  ### Construct log entry / Claimant Model statement.
  # Create the manifest.
  # This step needs to be a bash script in order to substitute the fake tag
  # in the command args.
  - name: golang
    entrypoint: bash
    args:
      - -c
      - |
        go run github.com/transparency-dev/armored-witness/cmd/manifest@main \
          create \
          --git_tag=$(cat /workspace/fake_tag) \
          --git_commit_fingerprint=${COMMIT_SHA} \
          --firmware_file=output/trusted_os.elf \
          --firmware_type=TRUSTED_OS \
          --tamago_version=${_TAMAGO_VERSION} \
          --raw \
          --output_file=output/trusted_os_manifest_unsigned.json
  # TODO: sign the log entry with github.com/transparency-dev/armored-witness/cmd/sign
  # after we create presubmit keys.
  #
  # Print the content of the manifest.
  - name: bash
    args:
      - cat
      - output/trusted_os_manifest_unsigned.json
substitutions:
  # Note that to be a valid CloudBuild config these MUST all be strings.
  # Without explicit quotes, some things may be interpreted as other types since
  # this is a YAML file, so to avoid future tears let's keep these all quoted.
  #
  # Build-related.
  _FIRMWARE_BUCKET: 'armored-witness-firmware-ci-1'
  _TAMAGO_VERSION: '1.21.5'
  # This must correspond with the trailing number on the _FIRMWARE_BUCKET, _ORIGIN values.
  _KEY_VERSION: '1'
  _ORIGIN: 'transparency.dev/armored-witness/firmware_transparency/ci/1'
  _LOG_PUBLIC_KEY: 'transparency.dev-aw-ftlog-ci+f5479c1e+AR6gW0mycDtL17iM2uvQUThJsoiuSRirstEj9a5AdCCu'
  _APPLET_PUBLIC_KEY: 'transparency.dev-aw-applet-ci+3ff32e2c+AV1fgxtByjXuPjPfi0/7qTbEBlPGGCyxqr6ZlppoLOz3'
  _OS_PUBLIC_KEY1: 'transparency.dev-aw-os1-ci+7a0eaef3+AcsqvmrcKIbs21H2Bm2fWb6oFWn/9MmLGNc6NLJty2eQ'
  _OS_PUBLIC_KEY2: 'transparency.dev-aw-os2-ci+af8e4114+AbBJk5MgxRB+68KhGojhUdSt1ts5GAdRIT1Eq9zEkgQh'
  _DEBUG: '1'
